# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2dc302bb4671539b54a76a4d96189a12465ea63b2acb2ebf570e5ae90c0af60621d1dae0937eb16f011f97a6dc27a356cae450cd0d1ecea6b5226542c7392cb

test:
  secret_key_base: 4ee7095421864869816c474292a05a760647f06468a3363fdf9a1f41387d9787e058264c8da775f1ed80bf603dbe64ef58cd5dbf26b51cf09109c678a5ca3b50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
